owner: owner
repo: repo

sms:
  sms_host: sms host
  sms_prog: sms prog
  sms_name: sms server name
  sms_user: sms user
  sms_password: sms password

task_list:
  -
    name: geps_t639 00H
    type: sms-node
    trigger:
      -
        type: time
        time: '04:02:00'
    nodes:
      -
        node_path: /geps_t639/00
        check_list:
          -
            type: variable
            name: SMSDATE
            value:
              type: date
              operator: equal
              fields: current
          -
            type: status
            value:
              operator: in
              fields:
                - submitted
                - active
                - complete