"""create tables

Revision ID: 07dd3884295a
Revises: 
Create Date: 2016-09-20 12:31:58.949134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07dd3884295a'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('owner',
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('owner_name', sa.String(length=45), nullable=False),
    sa.Column('owner_type', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('owner_id')
    )
    op.create_index('index_owner_name', 'owner', ['owner_name'], unique=True)
    op.create_table('repo',
    sa.Column('repo_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('repo_name', sa.String(length=45), nullable=True),
    sa.Column('repo_type', sa.String(length=10), nullable=True),
    sa.Column('repo_description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('repo_id')
    )
    op.create_index('index_owner_repo', 'repo', ['owner_id', 'repo_name'], unique=True)
    op.create_table('tickets_64',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('stub', sa.CHAR(length=1), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('org',
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('org_name', sa.String(length=45), nullable=False),
    sa.Column('org_description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['owner.owner_id'], ),
    sa.PrimaryKeyConstraint('owner_id')
    )
    op.create_index('index_org_name', 'org', ['org_name'], unique=True)
    op.create_table('user',
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=45), nullable=False),
    sa.Column('user_description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['owner.owner_id'], ),
    sa.PrimaryKeyConstraint('owner_id')
    )
    op.create_table('dingtalk_user',
    sa.Column('dingtalk_user_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('dingtalk_member_userid', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.owner_id'], ),
    sa.PrimaryKeyConstraint('dingtalk_user_id')
    )
    op.create_table('org_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('relationship', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['org.owner_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.owner_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('index_org_user', 'org_user', ['org_id', 'user_id'], unique=True)
    op.create_table('dingtalk_warn_watch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repo_id', sa.Integer(), nullable=False),
    sa.Column('dingtalk_user_id', sa.Text(), nullable=False),
    sa.Column('start_date_time', sa.DateTime(), nullable=True),
    sa.Column('end_date_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dingtalk_user_id'], ['dingtalk_user.dingtalk_user_id'], ),
    sa.ForeignKeyConstraint(['repo_id'], ['repo.repo_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dingtalk_warn_watch')
    op.drop_index('index_org_user', table_name='org_user')
    op.drop_table('org_user')
    op.drop_table('dingtalk_user')
    op.drop_table('user')
    op.drop_index('index_org_name', table_name='org')
    op.drop_table('org')
    op.drop_table('tickets_64')
    op.drop_index('index_owner_repo', table_name='repo')
    op.drop_table('repo')
    op.drop_index('index_owner_name', table_name='owner')
    op.drop_table('owner')
    ### end Alembic commands ###
