celery_server:
  name: server name

  broker:
    rabbitmq:
      host: host ip
      port: port number

  backend:
    mysql:
      host: host ip
      port: port number
      user: user
      password: password

  task_routes:
    -
      pattern: "nmp_scheduler.celery_server.task.sms.*"
      queue: nmp_sms
    -
      pattern: "nmp_scheduler.celery_server.task.ecflow.*"
      queue: nmp_ecflow
    -
      pattern: "nmp_scheduler.celery_server.task.hpc"
      queue: nmp_hpc


celery_beat:
  schedule: /tmp/celerybeat-schedule
  beat_schedule:
    -
      name: collect_sms_suite_status
      task: nmp_scheduler.celery_server.task.sms.status.get_group_sms_status_task
      schedule:
        type: crontab
        param:
          minute: '*/2'
    -
      name: update_dingtalk_access_token
      task: nmp_scheduler.celery_server.task.cloud.update_dingtalk_token_task
      schedule:
        type: crontab
        param:
          minute: '*/30'
    -
      name: update_weixin_access_token
      task: nmp_scheduler.celery_server.task.cloud.update_weixin_token_task
      schedule:
        type: crontab
        param:
          minute: '*/30'
    -
      name: collect_hpc_disk_usage
      task: nmp_scheduler.celery_server.task.hpc.get_group_hpc_disk_usage_task
      schedule:
        type: crontab
        param:
          minute: '*/10'
    -
      name: collect_hpc_disk_space
      task: nmp_scheduler.celery_server.task.hpc.get_group_hpc_disk_space_task
      schedule:
        type: crontab
        param:
          minute: '*/10'
    -
      name: collect_loadleveler_jobs
      task: nmp_scheduler.celery_server.task.workload.loadleveler.get_group_jobs_task
      schedule:
        type: crontab
        param:
          minute: '*/5'

celery_task:
  task_config_file: ./task.develop.config.yaml