sms_status_task:
  hpc:
    user: user
    host: host
    password: password

  project:
    dir: nwpc-sms-collector
    program: python binary
    script: nwpc_sms_collector/sms_status_collector.py collect
    post:
      url: http://host:port/api/v3/workflow/repos/{owner}/{repo}/status

group_sms_status_task:
  -
    owner: owner
    repo: repo
    sms_user: sms_user
    sms_name: sms_name
    user: user
    password: password

ecflow_status_task:
  collector:
    user: user
    host: host
    password: password

  project:
    dir: /some/path/nwpc-system-collector/nwpc-ecflow-collector/nwpc_ecflow_collector
    program: /some/path/python3
    script: ecflow_status_collector.py collect
    post:
      url: http://host:port/api/v3/workflow/repos/{owner}/{repo}/status

group_ecflow_status_task:
  - owner: owner
    repo: repo
    ecflow_host: host
    ecflow_port: post


update_dingtalk_token_task:
  url: http://broker_host:broker_port/api/v2/dingtalk/access_token/get

update_weixin_token_task:
  url: http://broker_host:broker_port/api/v2/weixin/access_token/get

sms_node_task:
  project:
    dir: nwpc-sms-collector dir
    program: python binary
    script: nwpc_sms_collector/sms_node_collector.py variable
  repo_config_dir: ./sms_node_task
  post:
    url: http://host:port/api/v3/workflow/repos/{owner}/{repo}/node-check


hpc:
  disk_usage:
    project:
      dir: nwpc_hpc_collector dir
      program: python binary
      script: disk_usage.py collect --config=config_file_path
    task_group:
      -
        user: user
        password: password
        host: host
        port: port

  disk_space:
    project:
      dir: nwpc_hpc_collector dir
      program: python binary
      script: disk_space.py collect --config=config_file_path
    task_group:
      -
        user: user
        password: password
        host: host
        port: port

  loadleveler_status:
    project:
      dir: nwpc_hpc_collector dir
      program: python binary
      script: loadleveler_status.py collect --config=config_file_path
    task_group:
      -
        user: user
        password: password
        host: host
        port: port
